spring.datasource.url=${CI_DB_URL_JDBC}
spring.datasource.username=${CI_DB_USER}
spring.datasource.password=${CI_DB_PASSWORD}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CI_SUPABASE_JWKS_URL:}
