create type "public"."concept_suggestions_status" as enum ('PENDING', 'LINKED', 'REJECTED');
create type "public"."flag_content_type" as enum ('LESSON', 'QUEST');
create type "public"."lessons_moderation_status" as enum ('PENDING', 'APPROVED', 'UNPUBLISHED', 'REJECTED');
create type "public"."moderation_actions_decision" as enum ('APPROVE', 'REQUEST_EDITS', 'UNPUBLISHED');
create type "public"."moderation_status" as enum ('PENDING', 'APPROVED', 'REJECTED');
create type "public"."quest_submission_media_type" as enum ('AUDIO', 'VIDEO', 'PHOTO');
create type "public"."quest_submission_mode" as enum ('VIDEO_WITH_CAPTION');
create type "public"."quest_submission_visibility" as enum ('SELF', 'FRIENDS', 'PUBLIC');
create type "public"."quiz_question_type" as enum ('MCQ', 'SHORT_ANSWER');
create type "public"."section_type" as enum ('TEXT', 'EXAMPLE', 'CALLOUT', 'DEFINITION', 'COMPARISON');
create type "public"."weekly_quest_activation_source" as enum ('ADMIN', 'FALLBACK');
create type "public"."weekly_quest_assignment_source_type" as enum ('ADMIN', 'FALLBACK', 'AI');
create type "public"."weekly_quest_assignment_status" as enum ('DRAFT', 'LOCKED', 'ACTIVE', 'RETIRED');
create type "public"."weekly_quest_week_status" as enum ('SCHEDULED', 'ACTIVE', 'COMPLETED');
create sequence "public"."quest_templates_id_seq";
create sequence "public"."weekly_quest_assignments_id_seq";
create sequence "public"."weekly_quest_challenge_submissions_id_seq";
create sequence "public"."weekly_quest_reminders_id_seq";
create sequence "public"."weekly_quest_weeks_id_seq";
create table "public"."admins" (
    "admin_id" uuid not null default auth.uid(),
    "created_at" timestamp with time zone not null default now()
      );
alter table "public"."admins" enable row level security;
create table "public"."concepts" (
    "concept_id" integer generated by default as identity not null,
    "title" character varying not null,
    "description" text not null,
    "created_at" timestamp with time zone not null,
    "public_id" uuid not null default gen_random_uuid()
      );
alter table "public"."concepts" enable row level security;
create table "public"."contributor_applications" (
    "contributor_application_id" bigint generated by default as identity not null,
    "public_id" uuid not null default gen_random_uuid(),
    "learner_id" uuid not null,
    "status" public.moderation_status not null,
    "submitted_at" timestamp with time zone not null default now(),
    "reviewed_at" timestamp with time zone,
    "rejection_reason" text
      );
alter table "public"."contributor_applications" enable row level security;
create table "public"."contributors" (
    "promoted_at" timestamp with time zone not null,
    "contributor_id" uuid not null,
    "total_points" smallint,
    "demoted_at" timestamp with time zone
      );
alter table "public"."contributors" enable row level security;
create table "public"."daily_concept_queue" (
    "queue_id" integer generated by default as identity not null,
    "concept_date" date not null,
    "concept_id" integer not null,
    "display_order" smallint not null
      );
alter table "public"."daily_concept_queue" enable row level security;
create table "public"."flags" (
    "flag_id" integer generated by default as identity not null,
    "content_type" public.flag_content_type not null,
    "content_id" integer not null,
    "reason" text not null,
    "flagged_at" timestamp with time zone not null,
    "learner_id" uuid not null
      );
alter table "public"."flags" enable row level security;
create table "public"."friend_requests" (
    "friend_request_id" bigint generated always as identity not null,
    "sender_id" uuid not null,
    "receiver_id" uuid not null,
    "status" text not null,
    "created_at" timestamp with time zone not null default now(),
    "responded_at" timestamp with time zone
      );
alter table "public"."friend_requests" enable row level security;
create table "public"."friends" (
    "user_id_1" uuid not null,
    "user_id_2" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );
alter table "public"."friends" enable row level security;
create table "public"."learners" (
    "id" uuid not null,
    "username" text,
    "created_at" timestamp with time zone not null default now(),
    "total_points" smallint not null,
    "public_id" uuid not null default gen_random_uuid()
      );
alter table "public"."learners" enable row level security;
create table "public"."lesson_concepts" (
    "lesson_id" integer not null,
    "concept_id" integer not null
      );
alter table "public"."lesson_concepts" enable row level security;
create table "public"."lesson_enrollments" (
    "enrollment_id" integer generated by default as identity not null,
    "lesson_id" integer not null,
    "completed" boolean not null default false,
    "first_completed_at" timestamp with time zone,
    "learner_id" uuid not null
      );
alter table "public"."lesson_enrollments" enable row level security;
create table "public"."lesson_moderation_records" (
    "lesson_moderation_record_id" integer generated by default as identity not null,
    "lesson_id" integer not null,
    "event_type" character varying not null,
    "decision_source" character varying not null,
    "resulting_status" public.lessons_moderation_status not null,
    "recorded_at" timestamp with time zone not null default now(),
    "reasons" jsonb not null default '[]'::jsonb,
    "failure_message" text,
    "raw_response" jsonb,
    "review_note" text,
    "actor_user_id" uuid,
    "provider_name" character varying
      );
alter table "public"."lesson_moderation_records" enable row level security;
create table "public"."lesson_sections" (
    "section_id" integer generated always as identity not null,
    "public_id" uuid not null default gen_random_uuid(),
    "lesson_id" integer not null,
    "order_index" smallint not null,
    "section_type" public.section_type not null,
    "title" character varying,
    "content" jsonb not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );
alter table "public"."lesson_sections" enable row level security;
create table "public"."lessons" (
    "lesson_id" integer generated by default as identity not null,
    "title" character varying not null,
    "moderation_status" public.lessons_moderation_status not null,
    "created_at" timestamp with time zone not null,
    "contributor_id" uuid not null,
    "content" jsonb,
    "deleted_at" timestamp with time zone,
    "public_id" uuid not null default gen_random_uuid()
      );
alter table "public"."lessons" enable row level security;
create table "public"."mcq_questions" (
    "question_id" bigint generated by default as identity not null,
    "options" jsonb not null,
    "correct_option_id" text
      );
alter table "public"."mcq_questions" enable row level security;
create table "public"."multi_select_questions" (
    "question_id" bigint generated by default as identity not null,
    "options" jsonb not null,
    "correct_option_ids" jsonb not null
      );
alter table "public"."multi_select_questions" enable row level security;
create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "public_id" uuid not null default gen_random_uuid(),
    "learner_id" uuid not null default gen_random_uuid(),
    "message" text,
    "is_read" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
      );
alter table "public"."notifications" enable row level security;
create table "public"."quest_templates" (
    "id" bigint not null default nextval('public.quest_templates_id_seq'::regclass),
    "public_id" uuid not null,
    "code" character varying(100) not null,
    "title" character varying(255) not null,
    "instruction_text" text not null,
    "submission_mode" public.quest_submission_mode not null,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null
      );
alter table "public"."quest_templates" enable row level security;
create table "public"."quiz_attempts" (
    "attempt_id" integer generated by default as identity not null,
    "quiz_id" integer not null,
    "score" smallint not null,
    "is_first_attempt" boolean not null,
    "attempted_at" timestamp with time zone not null,
    "learner_id" uuid not null
      );
alter table "public"."quiz_attempts" enable row level security;
create table "public"."quiz_questions" (
    "question_id" bigint generated by default as identity not null,
    "quiz_id" integer not null,
    "public_id" uuid not null default gen_random_uuid(),
    "question_type" text not null default ''::text,
    "prompt" text not null default ''::text,
    "order_index" integer not null default 0
      );
alter table "public"."quiz_questions" enable row level security;
create table "public"."quizzes" (
    "quiz_id" integer generated by default as identity not null,
    "lesson_id" bigint not null,
    "public_id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now()
      );
alter table "public"."quizzes" enable row level security;
create table "public"."true_false_questions" (
    "question_id" bigint generated by default as identity not null,
    "correct_boolean" boolean not null
      );
alter table "public"."true_false_questions" enable row level security;
create table "public"."weekly_quest_assignments" (
    "id" bigint not null default nextval('public.weekly_quest_assignments_id_seq'::regclass),
    "public_id" uuid not null,
    "week_id" bigint not null,
    "concept_id" integer not null,
    "quest_template_id" bigint not null,
    "slot_index" smallint not null default 0,
    "is_official" boolean not null default true,
    "source_type" public.weekly_quest_assignment_source_type not null,
    "status" public.weekly_quest_assignment_status not null,
    "created_by_admin_id" uuid,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone not null
      );
alter table "public"."weekly_quest_assignments" enable row level security;
create table "public"."weekly_quest_challenge_submissions" (
    "id" bigint not null default nextval('public.weekly_quest_challenge_submissions_id_seq'::regclass),
    "public_id" uuid not null,
    "learner_id" uuid not null,
    "weekly_quest_assignment_id" bigint not null,
    "media_object_key" text not null,
    "media_public_url" text,
    "media_content_type" character varying(255) not null,
    "original_filename" text not null,
    "file_size_bytes" bigint not null,
    "caption" text,
    "submitted_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone not null,
    "visibility" public.quest_submission_visibility not null default 'PUBLIC'::public.quest_submission_visibility
      );
alter table "public"."weekly_quest_challenge_submissions" enable row level security;
create table "public"."weekly_quest_reminders" (
    "id" bigint not null default nextval('public.weekly_quest_reminders_id_seq'::regclass),
    "week_id" bigint not null,
    "reminder_type" character varying(50) not null,
    "sent_at" timestamp with time zone not null
      );
alter table "public"."weekly_quest_reminders" enable row level security;
create table "public"."weekly_quest_weeks" (
    "id" bigint not null default nextval('public.weekly_quest_weeks_id_seq'::regclass),
    "public_id" uuid not null,
    "week_start_at" timestamp with time zone not null,
    "setup_deadline_at" timestamp with time zone not null,
    "status" public.weekly_quest_week_status not null,
    "activation_source" public.weekly_quest_activation_source not null,
    "activated_at" timestamp with time zone,
    "created_at" timestamp with time zone not null
      );
alter table "public"."weekly_quest_weeks" enable row level security;
alter sequence "public"."quest_templates_id_seq" owned by "public"."quest_templates"."id";
alter sequence "public"."weekly_quest_assignments_id_seq" owned by "public"."weekly_quest_assignments"."id";
alter sequence "public"."weekly_quest_challenge_submissions_id_seq" owned by "public"."weekly_quest_challenge_submissions"."id";
alter sequence "public"."weekly_quest_reminders_id_seq" owned by "public"."weekly_quest_reminders"."id";
alter sequence "public"."weekly_quest_weeks_id_seq" owned by "public"."weekly_quest_weeks"."id";
CREATE UNIQUE INDEX admins_pkey ON public.admins USING btree (admin_id);
CREATE UNIQUE INDEX concepts_pkey ON public.concepts USING btree (concept_id);
CREATE UNIQUE INDEX contributor_applications_pkey ON public.contributor_applications USING btree (contributor_application_id);
CREATE UNIQUE INDEX contributor_applications_public_id_key ON public.contributor_applications USING btree (public_id);
CREATE UNIQUE INDEX contributors_pkey ON public.contributors USING btree (contributor_id);
CREATE UNIQUE INDEX daily_concept_queue_pkey ON public.daily_concept_queue USING btree (queue_id);
CREATE UNIQUE INDEX flags_pkey ON public.flags USING btree (flag_id);
CREATE UNIQUE INDEX friend_requests_pkey ON public.friend_requests USING btree (friend_request_id);
CREATE UNIQUE INDEX friend_requests_unique_pair ON public.friend_requests USING btree (sender_id, receiver_id);
CREATE UNIQUE INDEX friends_pkey ON public.friends USING btree (user_id_1, user_id_2);
CREATE INDEX idx_lesson_sections_lesson_id ON public.lesson_sections USING btree (lesson_id);
CREATE INDEX idx_lesson_sections_lesson_order ON public.lesson_sections USING btree (lesson_id, order_index);
CREATE INDEX idx_weekly_quest_challenge_submissions_assignment ON public.weekly_quest_challenge_submissions USING btree (weekly_quest_assignment_id);
CREATE INDEX idx_weekly_quest_challenge_submissions_learner ON public.weekly_quest_challenge_submissions USING btree (learner_id);
CREATE INDEX ix_lesson_moderation_records_lesson_id ON public.lesson_moderation_records USING btree (lesson_id);
CREATE INDEX ix_lesson_moderation_records_lesson_id_recorded_at_desc ON public.lesson_moderation_records USING btree (lesson_id, recorded_at DESC);
CREATE INDEX ix_lesson_moderation_records_resulting_status ON public.lesson_moderation_records USING btree (resulting_status);
CREATE UNIQUE INDEX lesson_concepts_pkey ON public.lesson_concepts USING btree (lesson_id, concept_id);
CREATE UNIQUE INDEX lesson_enrollments_pkey ON public.lesson_enrollments USING btree (enrollment_id);
CREATE UNIQUE INDEX lesson_moderation_records_pkey ON public.lesson_moderation_records USING btree (lesson_moderation_record_id);
CREATE UNIQUE INDEX lesson_sections_order_unique ON public.lesson_sections USING btree (lesson_id, order_index);
CREATE UNIQUE INDEX lesson_sections_pkey ON public.lesson_sections USING btree (section_id);
CREATE UNIQUE INDEX lesson_sections_public_id_unique ON public.lesson_sections USING btree (public_id);
CREATE UNIQUE INDEX lessons_pkey ON public.lessons USING btree (lesson_id);
CREATE UNIQUE INDEX mcq_questions_pkey ON public.multi_select_questions USING btree (question_id);
CREATE UNIQUE INDEX mcq_questions_pkey1 ON public.mcq_questions USING btree (question_id);
CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);
CREATE UNIQUE INDEX notifications_public_id_key ON public.notifications USING btree (public_id);
CREATE UNIQUE INDEX profiles_pkey ON public.learners USING btree (id);
CREATE UNIQUE INDEX profiles_username_key ON public.learners USING btree (username);
CREATE UNIQUE INDEX quest_templates_code_key ON public.quest_templates USING btree (code);
CREATE UNIQUE INDEX quest_templates_pkey ON public.quest_templates USING btree (id);
CREATE UNIQUE INDEX quest_templates_public_id_key ON public.quest_templates USING btree (public_id);
CREATE UNIQUE INDEX quiz_attempts_pkey ON public.quiz_attempts USING btree (attempt_id);
CREATE UNIQUE INDEX quiz_questions_pkey ON public.quiz_questions USING btree (question_id);
CREATE UNIQUE INDEX quiz_questions_public_id_key ON public.quiz_questions USING btree (public_id);
CREATE UNIQUE INDEX quizzes_pkey ON public.quizzes USING btree (quiz_id);
CREATE UNIQUE INDEX quizzes_public_id_key ON public.quizzes USING btree (public_id);
CREATE UNIQUE INDEX true_false_questions_pkey ON public.true_false_questions USING btree (question_id);
CREATE UNIQUE INDEX uq_concepts_public_id ON public.concepts USING btree (public_id);
CREATE UNIQUE INDEX uq_learners_public_id ON public.learners USING btree (public_id);
CREATE UNIQUE INDEX uq_lessons_public_id ON public.lessons USING btree (public_id);
CREATE UNIQUE INDEX uq_weekly_quest_challenge_submission_learner_assignment ON public.weekly_quest_challenge_submissions USING btree (learner_id, weekly_quest_assignment_id);
CREATE INDEX weekly_quest_assignments_concept_id_idx ON public.weekly_quest_assignments USING btree (concept_id);
CREATE UNIQUE INDEX weekly_quest_assignments_one_official_per_week_uidx ON public.weekly_quest_assignments USING btree (week_id) WHERE (is_official = true);
CREATE UNIQUE INDEX weekly_quest_assignments_pkey ON public.weekly_quest_assignments USING btree (id);
CREATE UNIQUE INDEX weekly_quest_assignments_public_id_key ON public.weekly_quest_assignments USING btree (public_id);
CREATE INDEX weekly_quest_assignments_week_id_idx ON public.weekly_quest_assignments USING btree (week_id);
CREATE UNIQUE INDEX weekly_quest_assignments_week_slot_uidx ON public.weekly_quest_assignments USING btree (week_id, slot_index);
CREATE UNIQUE INDEX weekly_quest_challenge_submissions_pkey ON public.weekly_quest_challenge_submissions USING btree (id);
CREATE UNIQUE INDEX weekly_quest_challenge_submissions_public_id_key ON public.weekly_quest_challenge_submissions USING btree (public_id);
CREATE UNIQUE INDEX weekly_quest_reminders_pkey ON public.weekly_quest_reminders USING btree (id);
CREATE INDEX weekly_quest_reminders_type_sent_at_idx ON public.weekly_quest_reminders USING btree (reminder_type, sent_at);
CREATE INDEX weekly_quest_reminders_week_id_idx ON public.weekly_quest_reminders USING btree (week_id);
CREATE UNIQUE INDEX weekly_quest_weeks_pkey ON public.weekly_quest_weeks USING btree (id);
CREATE UNIQUE INDEX weekly_quest_weeks_public_id_key ON public.weekly_quest_weeks USING btree (public_id);
CREATE INDEX weekly_quest_weeks_status_week_start_idx ON public.weekly_quest_weeks USING btree (status, week_start_at);
CREATE UNIQUE INDEX weekly_quest_weeks_week_start_at_key ON public.weekly_quest_weeks USING btree (week_start_at);
alter table "public"."admins" add constraint "admins_pkey" PRIMARY KEY using index "admins_pkey";
alter table "public"."concepts" add constraint "concepts_pkey" PRIMARY KEY using index "concepts_pkey";
alter table "public"."contributor_applications" add constraint "contributor_applications_pkey" PRIMARY KEY using index "contributor_applications_pkey";
alter table "public"."contributors" add constraint "contributors_pkey" PRIMARY KEY using index "contributors_pkey";
alter table "public"."daily_concept_queue" add constraint "daily_concept_queue_pkey" PRIMARY KEY using index "daily_concept_queue_pkey";
alter table "public"."flags" add constraint "flags_pkey" PRIMARY KEY using index "flags_pkey";
alter table "public"."friend_requests" add constraint "friend_requests_pkey" PRIMARY KEY using index "friend_requests_pkey";
alter table "public"."friends" add constraint "friends_pkey" PRIMARY KEY using index "friends_pkey";
alter table "public"."learners" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";
alter table "public"."lesson_concepts" add constraint "lesson_concepts_pkey" PRIMARY KEY using index "lesson_concepts_pkey";
alter table "public"."lesson_enrollments" add constraint "lesson_enrollments_pkey" PRIMARY KEY using index "lesson_enrollments_pkey";
alter table "public"."lesson_moderation_records" add constraint "lesson_moderation_records_pkey" PRIMARY KEY using index "lesson_moderation_records_pkey";
alter table "public"."lesson_sections" add constraint "lesson_sections_pkey" PRIMARY KEY using index "lesson_sections_pkey";
alter table "public"."lessons" add constraint "lessons_pkey" PRIMARY KEY using index "lessons_pkey";
alter table "public"."mcq_questions" add constraint "mcq_questions_pkey1" PRIMARY KEY using index "mcq_questions_pkey1";
alter table "public"."multi_select_questions" add constraint "mcq_questions_pkey" PRIMARY KEY using index "mcq_questions_pkey";
alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";
alter table "public"."quest_templates" add constraint "quest_templates_pkey" PRIMARY KEY using index "quest_templates_pkey";
alter table "public"."quiz_attempts" add constraint "quiz_attempts_pkey" PRIMARY KEY using index "quiz_attempts_pkey";
alter table "public"."quiz_questions" add constraint "quiz_questions_pkey" PRIMARY KEY using index "quiz_questions_pkey";
alter table "public"."quizzes" add constraint "quizzes_pkey" PRIMARY KEY using index "quizzes_pkey";
alter table "public"."true_false_questions" add constraint "true_false_questions_pkey" PRIMARY KEY using index "true_false_questions_pkey";
alter table "public"."weekly_quest_assignments" add constraint "weekly_quest_assignments_pkey" PRIMARY KEY using index "weekly_quest_assignments_pkey";
alter table "public"."weekly_quest_challenge_submissions" add constraint "weekly_quest_challenge_submissions_pkey" PRIMARY KEY using index "weekly_quest_challenge_submissions_pkey";
alter table "public"."weekly_quest_reminders" add constraint "weekly_quest_reminders_pkey" PRIMARY KEY using index "weekly_quest_reminders_pkey";
alter table "public"."weekly_quest_weeks" add constraint "weekly_quest_weeks_pkey" PRIMARY KEY using index "weekly_quest_weeks_pkey";
alter table "public"."admins" add constraint "admins_admin_id_fkey" FOREIGN KEY (admin_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;
alter table "public"."admins" validate constraint "admins_admin_id_fkey";
alter table "public"."contributor_applications" add constraint "contributor_applications_learner_id_fkey" FOREIGN KEY (learner_id) REFERENCES public.learners(id) not valid;
alter table "public"."contributor_applications" validate constraint "contributor_applications_learner_id_fkey";
alter table "public"."contributor_applications" add constraint "contributor_applications_public_id_key" UNIQUE using index "contributor_applications_public_id_key";
alter table "public"."contributors" add constraint "contributors_profile_id_fkey" FOREIGN KEY (contributor_id) REFERENCES public.learners(id) not valid;
alter table "public"."contributors" validate constraint "contributors_profile_id_fkey";
alter table "public"."daily_concept_queue" add constraint "daily_concept_queue_concept_id_fkey" FOREIGN KEY (concept_id) REFERENCES public.concepts(concept_id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;
alter table "public"."daily_concept_queue" validate constraint "daily_concept_queue_concept_id_fkey";
alter table "public"."flags" add constraint "flags_learner_id_fkey" FOREIGN KEY (learner_id) REFERENCES public.learners(id) not valid;
alter table "public"."flags" validate constraint "flags_learner_id_fkey";
alter table "public"."friend_requests" add constraint "friend_requests_no_self" CHECK ((sender_id <> receiver_id)) not valid;
alter table "public"."friend_requests" validate constraint "friend_requests_no_self";
alter table "public"."friend_requests" add constraint "friend_requests_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public.learners(id) not valid;
alter table "public"."friend_requests" validate constraint "friend_requests_receiver_id_fkey";
alter table "public"."friend_requests" add constraint "friend_requests_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public.learners(id) not valid;
alter table "public"."friend_requests" validate constraint "friend_requests_sender_id_fkey";
alter table "public"."friend_requests" add constraint "friend_requests_status_check" CHECK ((status = ANY (ARRAY['PENDING'::text, 'APPROVED'::text, 'REJECTED'::text]))) not valid;
alter table "public"."friend_requests" validate constraint "friend_requests_status_check";
alter table "public"."friend_requests" add constraint "friend_requests_unique_pair" UNIQUE using index "friend_requests_unique_pair";
alter table "public"."friends" add constraint "friends_no_self" CHECK ((user_id_1 <> user_id_2)) not valid;
alter table "public"."friends" validate constraint "friends_no_self";
alter table "public"."friends" add constraint "friends_order_check" CHECK ((user_id_1 < user_id_2)) not valid;
alter table "public"."friends" validate constraint "friends_order_check";
alter table "public"."friends" add constraint "friends_user_id_1_fkey" FOREIGN KEY (user_id_1) REFERENCES public.learners(id) not valid;
alter table "public"."friends" validate constraint "friends_user_id_1_fkey";
alter table "public"."friends" add constraint "friends_user_id_2_fkey" FOREIGN KEY (user_id_2) REFERENCES public.learners(id) not valid;
alter table "public"."friends" validate constraint "friends_user_id_2_fkey";
alter table "public"."learners" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."learners" validate constraint "profiles_id_fkey";
alter table "public"."learners" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";
alter table "public"."lesson_concepts" add constraint "lesson_concepts_concept_id_fkey" FOREIGN KEY (concept_id) REFERENCES public.concepts(concept_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."lesson_concepts" validate constraint "lesson_concepts_concept_id_fkey";
alter table "public"."lesson_concepts" add constraint "lesson_concepts_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."lesson_concepts" validate constraint "lesson_concepts_lesson_id_fkey";
alter table "public"."lesson_enrollments" add constraint "lesson_enrollments_learner_id_fkey" FOREIGN KEY (learner_id) REFERENCES public.learners(id) not valid;
alter table "public"."lesson_enrollments" validate constraint "lesson_enrollments_learner_id_fkey";
alter table "public"."lesson_enrollments" add constraint "lesson_enrollments_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;
alter table "public"."lesson_enrollments" validate constraint "lesson_enrollments_lesson_id_fkey";
alter table "public"."lesson_moderation_records" add constraint "lesson_moderation_records_decision_source_check" CHECK (((decision_source)::text = ANY ((ARRAY['AUTO'::character varying, 'AUTO_FALLBACK'::character varying, 'ADMIN'::character varying])::text[]))) not valid;
alter table "public"."lesson_moderation_records" validate constraint "lesson_moderation_records_decision_source_check";
alter table "public"."lesson_moderation_records" add constraint "lesson_moderation_records_event_type_check" CHECK (((event_type)::text = ANY ((ARRAY['AUTO_APPROVED'::character varying, 'AUTO_REJECTED'::character varying, 'AUTO_FLAGGED'::character varying, 'AUTO_FAILED'::character varying, 'ADMIN_APPROVED'::character varying, 'ADMIN_REJECTED'::character varying])::text[]))) not valid;
alter table "public"."lesson_moderation_records" validate constraint "lesson_moderation_records_event_type_check";
alter table "public"."lesson_moderation_records" add constraint "lesson_moderation_records_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."lesson_moderation_records" validate constraint "lesson_moderation_records_lesson_id_fkey";
alter table "public"."lesson_sections" add constraint "lesson_sections_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON DELETE CASCADE not valid;
alter table "public"."lesson_sections" validate constraint "lesson_sections_lesson_id_fkey";
alter table "public"."lesson_sections" add constraint "lesson_sections_order_unique" UNIQUE using index "lesson_sections_order_unique";
alter table "public"."lesson_sections" add constraint "lesson_sections_public_id_unique" UNIQUE using index "lesson_sections_public_id_unique";
alter table "public"."lessons" add constraint "lessons_contributor_id_fkey" FOREIGN KEY (contributor_id) REFERENCES public.contributors(contributor_id) not valid;
alter table "public"."lessons" validate constraint "lessons_contributor_id_fkey";
alter table "public"."mcq_questions" add constraint "mcq_questions_question_id_fkey1" FOREIGN KEY (question_id) REFERENCES public.quiz_questions(question_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."mcq_questions" validate constraint "mcq_questions_question_id_fkey1";
alter table "public"."multi_select_questions" add constraint "mcq_questions_question_id_fkey" FOREIGN KEY (question_id) REFERENCES public.quiz_questions(question_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."multi_select_questions" validate constraint "mcq_questions_question_id_fkey";
alter table "public"."notifications" add constraint "notifications_learner_id_fkey" FOREIGN KEY (learner_id) REFERENCES public.learners(id) not valid;
alter table "public"."notifications" validate constraint "notifications_learner_id_fkey";
alter table "public"."notifications" add constraint "notifications_public_id_key" UNIQUE using index "notifications_public_id_key";
alter table "public"."quest_templates" add constraint "quest_templates_code_key" UNIQUE using index "quest_templates_code_key";
alter table "public"."quest_templates" add constraint "quest_templates_public_id_key" UNIQUE using index "quest_templates_public_id_key";
alter table "public"."quiz_attempts" add constraint "quiz_attempts_learner_id_fkey" FOREIGN KEY (learner_id) REFERENCES public.learners(id) not valid;
alter table "public"."quiz_attempts" validate constraint "quiz_attempts_learner_id_fkey";
alter table "public"."quiz_attempts" add constraint "quiz_attempts_quiz_id_fkey" FOREIGN KEY (quiz_id) REFERENCES public.quizzes(quiz_id) not valid;
alter table "public"."quiz_attempts" validate constraint "quiz_attempts_quiz_id_fkey";
alter table "public"."quiz_questions" add constraint "quiz_questions_public_id_key" UNIQUE using index "quiz_questions_public_id_key";
alter table "public"."quiz_questions" add constraint "quiz_questions_quiz_id_fkey" FOREIGN KEY (quiz_id) REFERENCES public.quizzes(quiz_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."quiz_questions" validate constraint "quiz_questions_quiz_id_fkey";
alter table "public"."quizzes" add constraint "quizzes_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;
alter table "public"."quizzes" validate constraint "quizzes_lesson_id_fkey";
alter table "public"."quizzes" add constraint "quizzes_public_id_key" UNIQUE using index "quizzes_public_id_key";
alter table "public"."true_false_questions" add constraint "true_false_questions_question_id_fkey" FOREIGN KEY (question_id) REFERENCES public.quiz_questions(question_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."true_false_questions" validate constraint "true_false_questions_question_id_fkey";
alter table "public"."weekly_quest_assignments" add constraint "weekly_quest_assignments_concept_id_fkey" FOREIGN KEY (concept_id) REFERENCES public.concepts(concept_id) not valid;
alter table "public"."weekly_quest_assignments" validate constraint "weekly_quest_assignments_concept_id_fkey";
alter table "public"."weekly_quest_assignments" add constraint "weekly_quest_assignments_public_id_key" UNIQUE using index "weekly_quest_assignments_public_id_key";
alter table "public"."weekly_quest_assignments" add constraint "weekly_quest_assignments_quest_template_id_fkey" FOREIGN KEY (quest_template_id) REFERENCES public.quest_templates(id) not valid;
alter table "public"."weekly_quest_assignments" validate constraint "weekly_quest_assignments_quest_template_id_fkey";
alter table "public"."weekly_quest_assignments" add constraint "weekly_quest_assignments_slot_index_check" CHECK ((slot_index >= 0)) not valid;
alter table "public"."weekly_quest_assignments" validate constraint "weekly_quest_assignments_slot_index_check";
alter table "public"."weekly_quest_assignments" add constraint "weekly_quest_assignments_week_id_fkey" FOREIGN KEY (week_id) REFERENCES public.weekly_quest_weeks(id) not valid;
alter table "public"."weekly_quest_assignments" validate constraint "weekly_quest_assignments_week_id_fkey";
alter table "public"."weekly_quest_challenge_submissions" add constraint "fk_weekly_quest_challenge_submissions_assignment" FOREIGN KEY (weekly_quest_assignment_id) REFERENCES public.weekly_quest_assignments(id) not valid;
alter table "public"."weekly_quest_challenge_submissions" validate constraint "fk_weekly_quest_challenge_submissions_assignment";
alter table "public"."weekly_quest_challenge_submissions" add constraint "fk_weekly_quest_challenge_submissions_learner" FOREIGN KEY (learner_id) REFERENCES public.learners(id) not valid;
alter table "public"."weekly_quest_challenge_submissions" validate constraint "fk_weekly_quest_challenge_submissions_learner";
alter table "public"."weekly_quest_challenge_submissions" add constraint "uq_weekly_quest_challenge_submission_learner_assignment" UNIQUE using index "uq_weekly_quest_challenge_submission_learner_assignment";
alter table "public"."weekly_quest_challenge_submissions" add constraint "weekly_quest_challenge_submissions_public_id_key" UNIQUE using index "weekly_quest_challenge_submissions_public_id_key";
alter table "public"."weekly_quest_reminders" add constraint "weekly_quest_reminders_week_id_fkey" FOREIGN KEY (week_id) REFERENCES public.weekly_quest_weeks(id) not valid;
alter table "public"."weekly_quest_reminders" validate constraint "weekly_quest_reminders_week_id_fkey";
alter table "public"."weekly_quest_weeks" add constraint "weekly_quest_weeks_public_id_key" UNIQUE using index "weekly_quest_weeks_public_id_key";
alter table "public"."weekly_quest_weeks" add constraint "weekly_quest_weeks_week_start_at_key" UNIQUE using index "weekly_quest_weeks_week_start_at_key";
set check_function_bodies = off;
CREATE OR REPLACE FUNCTION public.create_profile_on_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.learners (id, username, total_points, created_at)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data->>'username',  -- Try to get username from metadata
      split_part(NEW.email, '@', 1)         -- Fallback to email prefix
    ),
    0,                                       -- Initialize points to 0
    NOW()
  );
  
  RETURN NEW;
END;
$function$;
grant delete on table "public"."admins" to "anon";
grant insert on table "public"."admins" to "anon";
grant references on table "public"."admins" to "anon";
grant select on table "public"."admins" to "anon";
grant trigger on table "public"."admins" to "anon";
grant truncate on table "public"."admins" to "anon";
grant update on table "public"."admins" to "anon";
grant delete on table "public"."admins" to "authenticated";
grant insert on table "public"."admins" to "authenticated";
grant references on table "public"."admins" to "authenticated";
grant select on table "public"."admins" to "authenticated";
grant trigger on table "public"."admins" to "authenticated";
grant truncate on table "public"."admins" to "authenticated";
grant update on table "public"."admins" to "authenticated";
grant delete on table "public"."admins" to "service_role";
grant insert on table "public"."admins" to "service_role";
grant references on table "public"."admins" to "service_role";
grant select on table "public"."admins" to "service_role";
grant trigger on table "public"."admins" to "service_role";
grant truncate on table "public"."admins" to "service_role";
grant update on table "public"."admins" to "service_role";
grant delete on table "public"."concepts" to "anon";
grant insert on table "public"."concepts" to "anon";
grant references on table "public"."concepts" to "anon";
grant select on table "public"."concepts" to "anon";
grant trigger on table "public"."concepts" to "anon";
grant truncate on table "public"."concepts" to "anon";
grant update on table "public"."concepts" to "anon";
grant delete on table "public"."concepts" to "authenticated";
grant insert on table "public"."concepts" to "authenticated";
grant references on table "public"."concepts" to "authenticated";
grant select on table "public"."concepts" to "authenticated";
grant trigger on table "public"."concepts" to "authenticated";
grant truncate on table "public"."concepts" to "authenticated";
grant update on table "public"."concepts" to "authenticated";
grant delete on table "public"."concepts" to "service_role";
grant insert on table "public"."concepts" to "service_role";
grant references on table "public"."concepts" to "service_role";
grant select on table "public"."concepts" to "service_role";
grant trigger on table "public"."concepts" to "service_role";
grant truncate on table "public"."concepts" to "service_role";
grant update on table "public"."concepts" to "service_role";
grant delete on table "public"."contributor_applications" to "anon";
grant insert on table "public"."contributor_applications" to "anon";
grant references on table "public"."contributor_applications" to "anon";
grant select on table "public"."contributor_applications" to "anon";
grant trigger on table "public"."contributor_applications" to "anon";
grant truncate on table "public"."contributor_applications" to "anon";
grant update on table "public"."contributor_applications" to "anon";
grant delete on table "public"."contributor_applications" to "authenticated";
grant insert on table "public"."contributor_applications" to "authenticated";
grant references on table "public"."contributor_applications" to "authenticated";
grant select on table "public"."contributor_applications" to "authenticated";
grant trigger on table "public"."contributor_applications" to "authenticated";
grant truncate on table "public"."contributor_applications" to "authenticated";
grant update on table "public"."contributor_applications" to "authenticated";
grant delete on table "public"."contributor_applications" to "service_role";
grant insert on table "public"."contributor_applications" to "service_role";
grant references on table "public"."contributor_applications" to "service_role";
grant select on table "public"."contributor_applications" to "service_role";
grant trigger on table "public"."contributor_applications" to "service_role";
grant truncate on table "public"."contributor_applications" to "service_role";
grant update on table "public"."contributor_applications" to "service_role";
grant delete on table "public"."contributors" to "anon";
grant insert on table "public"."contributors" to "anon";
grant references on table "public"."contributors" to "anon";
grant select on table "public"."contributors" to "anon";
grant trigger on table "public"."contributors" to "anon";
grant truncate on table "public"."contributors" to "anon";
grant update on table "public"."contributors" to "anon";
grant delete on table "public"."contributors" to "authenticated";
grant insert on table "public"."contributors" to "authenticated";
grant references on table "public"."contributors" to "authenticated";
grant select on table "public"."contributors" to "authenticated";
grant trigger on table "public"."contributors" to "authenticated";
grant truncate on table "public"."contributors" to "authenticated";
grant update on table "public"."contributors" to "authenticated";
grant delete on table "public"."contributors" to "service_role";
grant insert on table "public"."contributors" to "service_role";
grant references on table "public"."contributors" to "service_role";
grant select on table "public"."contributors" to "service_role";
grant trigger on table "public"."contributors" to "service_role";
grant truncate on table "public"."contributors" to "service_role";
grant update on table "public"."contributors" to "service_role";
grant delete on table "public"."daily_concept_queue" to "anon";
grant insert on table "public"."daily_concept_queue" to "anon";
grant references on table "public"."daily_concept_queue" to "anon";
grant select on table "public"."daily_concept_queue" to "anon";
grant trigger on table "public"."daily_concept_queue" to "anon";
grant truncate on table "public"."daily_concept_queue" to "anon";
grant update on table "public"."daily_concept_queue" to "anon";
grant delete on table "public"."daily_concept_queue" to "authenticated";
grant insert on table "public"."daily_concept_queue" to "authenticated";
grant references on table "public"."daily_concept_queue" to "authenticated";
grant select on table "public"."daily_concept_queue" to "authenticated";
grant trigger on table "public"."daily_concept_queue" to "authenticated";
grant truncate on table "public"."daily_concept_queue" to "authenticated";
grant update on table "public"."daily_concept_queue" to "authenticated";
grant delete on table "public"."daily_concept_queue" to "service_role";
grant insert on table "public"."daily_concept_queue" to "service_role";
grant references on table "public"."daily_concept_queue" to "service_role";
grant select on table "public"."daily_concept_queue" to "service_role";
grant trigger on table "public"."daily_concept_queue" to "service_role";
grant truncate on table "public"."daily_concept_queue" to "service_role";
grant update on table "public"."daily_concept_queue" to "service_role";
grant delete on table "public"."flags" to "anon";
grant insert on table "public"."flags" to "anon";
grant references on table "public"."flags" to "anon";
grant select on table "public"."flags" to "anon";
grant trigger on table "public"."flags" to "anon";
grant truncate on table "public"."flags" to "anon";
grant update on table "public"."flags" to "anon";
grant delete on table "public"."flags" to "authenticated";
grant insert on table "public"."flags" to "authenticated";
grant references on table "public"."flags" to "authenticated";
grant select on table "public"."flags" to "authenticated";
grant trigger on table "public"."flags" to "authenticated";
grant truncate on table "public"."flags" to "authenticated";
grant update on table "public"."flags" to "authenticated";
grant delete on table "public"."flags" to "service_role";
grant insert on table "public"."flags" to "service_role";
grant references on table "public"."flags" to "service_role";
grant select on table "public"."flags" to "service_role";
grant trigger on table "public"."flags" to "service_role";
grant truncate on table "public"."flags" to "service_role";
grant update on table "public"."flags" to "service_role";
grant delete on table "public"."friend_requests" to "anon";
grant insert on table "public"."friend_requests" to "anon";
grant references on table "public"."friend_requests" to "anon";
grant select on table "public"."friend_requests" to "anon";
grant trigger on table "public"."friend_requests" to "anon";
grant truncate on table "public"."friend_requests" to "anon";
grant update on table "public"."friend_requests" to "anon";
grant delete on table "public"."friend_requests" to "authenticated";
grant insert on table "public"."friend_requests" to "authenticated";
grant references on table "public"."friend_requests" to "authenticated";
grant select on table "public"."friend_requests" to "authenticated";
grant trigger on table "public"."friend_requests" to "authenticated";
grant truncate on table "public"."friend_requests" to "authenticated";
grant update on table "public"."friend_requests" to "authenticated";
grant delete on table "public"."friend_requests" to "service_role";
grant insert on table "public"."friend_requests" to "service_role";
grant references on table "public"."friend_requests" to "service_role";
grant select on table "public"."friend_requests" to "service_role";
grant trigger on table "public"."friend_requests" to "service_role";
grant truncate on table "public"."friend_requests" to "service_role";
grant update on table "public"."friend_requests" to "service_role";
grant delete on table "public"."friends" to "anon";
grant insert on table "public"."friends" to "anon";
grant references on table "public"."friends" to "anon";
grant select on table "public"."friends" to "anon";
grant trigger on table "public"."friends" to "anon";
grant truncate on table "public"."friends" to "anon";
grant update on table "public"."friends" to "anon";
grant delete on table "public"."friends" to "authenticated";
grant insert on table "public"."friends" to "authenticated";
grant references on table "public"."friends" to "authenticated";
grant select on table "public"."friends" to "authenticated";
grant trigger on table "public"."friends" to "authenticated";
grant truncate on table "public"."friends" to "authenticated";
grant update on table "public"."friends" to "authenticated";
grant delete on table "public"."friends" to "service_role";
grant insert on table "public"."friends" to "service_role";
grant references on table "public"."friends" to "service_role";
grant select on table "public"."friends" to "service_role";
grant trigger on table "public"."friends" to "service_role";
grant truncate on table "public"."friends" to "service_role";
grant update on table "public"."friends" to "service_role";
grant delete on table "public"."learners" to "anon";
grant insert on table "public"."learners" to "anon";
grant references on table "public"."learners" to "anon";
grant select on table "public"."learners" to "anon";
grant trigger on table "public"."learners" to "anon";
grant truncate on table "public"."learners" to "anon";
grant update on table "public"."learners" to "anon";
grant delete on table "public"."learners" to "authenticated";
grant insert on table "public"."learners" to "authenticated";
grant references on table "public"."learners" to "authenticated";
grant select on table "public"."learners" to "authenticated";
grant trigger on table "public"."learners" to "authenticated";
grant truncate on table "public"."learners" to "authenticated";
grant update on table "public"."learners" to "authenticated";
grant delete on table "public"."learners" to "service_role";
grant insert on table "public"."learners" to "service_role";
grant references on table "public"."learners" to "service_role";
grant select on table "public"."learners" to "service_role";
grant trigger on table "public"."learners" to "service_role";
grant truncate on table "public"."learners" to "service_role";
grant update on table "public"."learners" to "service_role";
grant delete on table "public"."lesson_concepts" to "anon";
grant insert on table "public"."lesson_concepts" to "anon";
grant references on table "public"."lesson_concepts" to "anon";
grant select on table "public"."lesson_concepts" to "anon";
grant trigger on table "public"."lesson_concepts" to "anon";
grant truncate on table "public"."lesson_concepts" to "anon";
grant update on table "public"."lesson_concepts" to "anon";
grant delete on table "public"."lesson_concepts" to "authenticated";
grant insert on table "public"."lesson_concepts" to "authenticated";
grant references on table "public"."lesson_concepts" to "authenticated";
grant select on table "public"."lesson_concepts" to "authenticated";
grant trigger on table "public"."lesson_concepts" to "authenticated";
grant truncate on table "public"."lesson_concepts" to "authenticated";
grant update on table "public"."lesson_concepts" to "authenticated";
grant delete on table "public"."lesson_concepts" to "service_role";
grant insert on table "public"."lesson_concepts" to "service_role";
grant references on table "public"."lesson_concepts" to "service_role";
grant select on table "public"."lesson_concepts" to "service_role";
grant trigger on table "public"."lesson_concepts" to "service_role";
grant truncate on table "public"."lesson_concepts" to "service_role";
grant update on table "public"."lesson_concepts" to "service_role";
grant delete on table "public"."lesson_enrollments" to "anon";
grant insert on table "public"."lesson_enrollments" to "anon";
grant references on table "public"."lesson_enrollments" to "anon";
grant select on table "public"."lesson_enrollments" to "anon";
grant trigger on table "public"."lesson_enrollments" to "anon";
grant truncate on table "public"."lesson_enrollments" to "anon";
grant update on table "public"."lesson_enrollments" to "anon";
grant delete on table "public"."lesson_enrollments" to "authenticated";
grant insert on table "public"."lesson_enrollments" to "authenticated";
grant references on table "public"."lesson_enrollments" to "authenticated";
grant select on table "public"."lesson_enrollments" to "authenticated";
grant trigger on table "public"."lesson_enrollments" to "authenticated";
grant truncate on table "public"."lesson_enrollments" to "authenticated";
grant update on table "public"."lesson_enrollments" to "authenticated";
grant delete on table "public"."lesson_enrollments" to "service_role";
grant insert on table "public"."lesson_enrollments" to "service_role";
grant references on table "public"."lesson_enrollments" to "service_role";
grant select on table "public"."lesson_enrollments" to "service_role";
grant trigger on table "public"."lesson_enrollments" to "service_role";
grant truncate on table "public"."lesson_enrollments" to "service_role";
grant update on table "public"."lesson_enrollments" to "service_role";
grant delete on table "public"."lesson_moderation_records" to "anon";
grant insert on table "public"."lesson_moderation_records" to "anon";
grant references on table "public"."lesson_moderation_records" to "anon";
grant select on table "public"."lesson_moderation_records" to "anon";
grant trigger on table "public"."lesson_moderation_records" to "anon";
grant truncate on table "public"."lesson_moderation_records" to "anon";
grant update on table "public"."lesson_moderation_records" to "anon";
grant delete on table "public"."lesson_moderation_records" to "authenticated";
grant insert on table "public"."lesson_moderation_records" to "authenticated";
grant references on table "public"."lesson_moderation_records" to "authenticated";
grant select on table "public"."lesson_moderation_records" to "authenticated";
grant trigger on table "public"."lesson_moderation_records" to "authenticated";
grant truncate on table "public"."lesson_moderation_records" to "authenticated";
grant update on table "public"."lesson_moderation_records" to "authenticated";
grant delete on table "public"."lesson_moderation_records" to "service_role";
grant insert on table "public"."lesson_moderation_records" to "service_role";
grant references on table "public"."lesson_moderation_records" to "service_role";
grant select on table "public"."lesson_moderation_records" to "service_role";
grant trigger on table "public"."lesson_moderation_records" to "service_role";
grant truncate on table "public"."lesson_moderation_records" to "service_role";
grant update on table "public"."lesson_moderation_records" to "service_role";
grant delete on table "public"."lesson_sections" to "anon";
grant insert on table "public"."lesson_sections" to "anon";
grant references on table "public"."lesson_sections" to "anon";
grant select on table "public"."lesson_sections" to "anon";
grant trigger on table "public"."lesson_sections" to "anon";
grant truncate on table "public"."lesson_sections" to "anon";
grant update on table "public"."lesson_sections" to "anon";
grant delete on table "public"."lesson_sections" to "authenticated";
grant insert on table "public"."lesson_sections" to "authenticated";
grant references on table "public"."lesson_sections" to "authenticated";
grant select on table "public"."lesson_sections" to "authenticated";
grant trigger on table "public"."lesson_sections" to "authenticated";
grant truncate on table "public"."lesson_sections" to "authenticated";
grant update on table "public"."lesson_sections" to "authenticated";
grant delete on table "public"."lesson_sections" to "service_role";
grant insert on table "public"."lesson_sections" to "service_role";
grant references on table "public"."lesson_sections" to "service_role";
grant select on table "public"."lesson_sections" to "service_role";
grant trigger on table "public"."lesson_sections" to "service_role";
grant truncate on table "public"."lesson_sections" to "service_role";
grant update on table "public"."lesson_sections" to "service_role";
grant delete on table "public"."lessons" to "anon";
grant insert on table "public"."lessons" to "anon";
grant references on table "public"."lessons" to "anon";
grant select on table "public"."lessons" to "anon";
grant trigger on table "public"."lessons" to "anon";
grant truncate on table "public"."lessons" to "anon";
grant update on table "public"."lessons" to "anon";
grant delete on table "public"."lessons" to "authenticated";
grant insert on table "public"."lessons" to "authenticated";
grant references on table "public"."lessons" to "authenticated";
grant select on table "public"."lessons" to "authenticated";
grant trigger on table "public"."lessons" to "authenticated";
grant truncate on table "public"."lessons" to "authenticated";
grant update on table "public"."lessons" to "authenticated";
grant delete on table "public"."lessons" to "service_role";
grant insert on table "public"."lessons" to "service_role";
grant references on table "public"."lessons" to "service_role";
grant select on table "public"."lessons" to "service_role";
grant trigger on table "public"."lessons" to "service_role";
grant truncate on table "public"."lessons" to "service_role";
grant update on table "public"."lessons" to "service_role";
grant delete on table "public"."mcq_questions" to "anon";
grant insert on table "public"."mcq_questions" to "anon";
grant references on table "public"."mcq_questions" to "anon";
grant select on table "public"."mcq_questions" to "anon";
grant trigger on table "public"."mcq_questions" to "anon";
grant truncate on table "public"."mcq_questions" to "anon";
grant update on table "public"."mcq_questions" to "anon";
grant delete on table "public"."mcq_questions" to "authenticated";
grant insert on table "public"."mcq_questions" to "authenticated";
grant references on table "public"."mcq_questions" to "authenticated";
grant select on table "public"."mcq_questions" to "authenticated";
grant trigger on table "public"."mcq_questions" to "authenticated";
grant truncate on table "public"."mcq_questions" to "authenticated";
grant update on table "public"."mcq_questions" to "authenticated";
grant delete on table "public"."mcq_questions" to "service_role";
grant insert on table "public"."mcq_questions" to "service_role";
grant references on table "public"."mcq_questions" to "service_role";
grant select on table "public"."mcq_questions" to "service_role";
grant trigger on table "public"."mcq_questions" to "service_role";
grant truncate on table "public"."mcq_questions" to "service_role";
grant update on table "public"."mcq_questions" to "service_role";
grant delete on table "public"."multi_select_questions" to "anon";
grant insert on table "public"."multi_select_questions" to "anon";
grant references on table "public"."multi_select_questions" to "anon";
grant select on table "public"."multi_select_questions" to "anon";
grant trigger on table "public"."multi_select_questions" to "anon";
grant truncate on table "public"."multi_select_questions" to "anon";
grant update on table "public"."multi_select_questions" to "anon";
grant delete on table "public"."multi_select_questions" to "authenticated";
grant insert on table "public"."multi_select_questions" to "authenticated";
grant references on table "public"."multi_select_questions" to "authenticated";
grant select on table "public"."multi_select_questions" to "authenticated";
grant trigger on table "public"."multi_select_questions" to "authenticated";
grant truncate on table "public"."multi_select_questions" to "authenticated";
grant update on table "public"."multi_select_questions" to "authenticated";
grant delete on table "public"."multi_select_questions" to "service_role";
grant insert on table "public"."multi_select_questions" to "service_role";
grant references on table "public"."multi_select_questions" to "service_role";
grant select on table "public"."multi_select_questions" to "service_role";
grant trigger on table "public"."multi_select_questions" to "service_role";
grant truncate on table "public"."multi_select_questions" to "service_role";
grant update on table "public"."multi_select_questions" to "service_role";
grant delete on table "public"."notifications" to "anon";
grant insert on table "public"."notifications" to "anon";
grant references on table "public"."notifications" to "anon";
grant select on table "public"."notifications" to "anon";
grant trigger on table "public"."notifications" to "anon";
grant truncate on table "public"."notifications" to "anon";
grant update on table "public"."notifications" to "anon";
grant delete on table "public"."notifications" to "authenticated";
grant insert on table "public"."notifications" to "authenticated";
grant references on table "public"."notifications" to "authenticated";
grant select on table "public"."notifications" to "authenticated";
grant trigger on table "public"."notifications" to "authenticated";
grant truncate on table "public"."notifications" to "authenticated";
grant update on table "public"."notifications" to "authenticated";
grant delete on table "public"."notifications" to "service_role";
grant insert on table "public"."notifications" to "service_role";
grant references on table "public"."notifications" to "service_role";
grant select on table "public"."notifications" to "service_role";
grant trigger on table "public"."notifications" to "service_role";
grant truncate on table "public"."notifications" to "service_role";
grant update on table "public"."notifications" to "service_role";
grant delete on table "public"."quest_templates" to "anon";
grant insert on table "public"."quest_templates" to "anon";
grant references on table "public"."quest_templates" to "anon";
grant select on table "public"."quest_templates" to "anon";
grant trigger on table "public"."quest_templates" to "anon";
grant truncate on table "public"."quest_templates" to "anon";
grant update on table "public"."quest_templates" to "anon";
grant delete on table "public"."quest_templates" to "authenticated";
grant insert on table "public"."quest_templates" to "authenticated";
grant references on table "public"."quest_templates" to "authenticated";
grant select on table "public"."quest_templates" to "authenticated";
grant trigger on table "public"."quest_templates" to "authenticated";
grant truncate on table "public"."quest_templates" to "authenticated";
grant update on table "public"."quest_templates" to "authenticated";
grant delete on table "public"."quest_templates" to "service_role";
grant insert on table "public"."quest_templates" to "service_role";
grant references on table "public"."quest_templates" to "service_role";
grant select on table "public"."quest_templates" to "service_role";
grant trigger on table "public"."quest_templates" to "service_role";
grant truncate on table "public"."quest_templates" to "service_role";
grant update on table "public"."quest_templates" to "service_role";
grant delete on table "public"."quiz_attempts" to "anon";
grant insert on table "public"."quiz_attempts" to "anon";
grant references on table "public"."quiz_attempts" to "anon";
grant select on table "public"."quiz_attempts" to "anon";
grant trigger on table "public"."quiz_attempts" to "anon";
grant truncate on table "public"."quiz_attempts" to "anon";
grant update on table "public"."quiz_attempts" to "anon";
grant delete on table "public"."quiz_attempts" to "authenticated";
grant insert on table "public"."quiz_attempts" to "authenticated";
grant references on table "public"."quiz_attempts" to "authenticated";
grant select on table "public"."quiz_attempts" to "authenticated";
grant trigger on table "public"."quiz_attempts" to "authenticated";
grant truncate on table "public"."quiz_attempts" to "authenticated";
grant update on table "public"."quiz_attempts" to "authenticated";
grant delete on table "public"."quiz_attempts" to "service_role";
grant insert on table "public"."quiz_attempts" to "service_role";
grant references on table "public"."quiz_attempts" to "service_role";
grant select on table "public"."quiz_attempts" to "service_role";
grant trigger on table "public"."quiz_attempts" to "service_role";
grant truncate on table "public"."quiz_attempts" to "service_role";
grant update on table "public"."quiz_attempts" to "service_role";
grant delete on table "public"."quiz_questions" to "anon";
grant insert on table "public"."quiz_questions" to "anon";
grant references on table "public"."quiz_questions" to "anon";
grant select on table "public"."quiz_questions" to "anon";
grant trigger on table "public"."quiz_questions" to "anon";
grant truncate on table "public"."quiz_questions" to "anon";
grant update on table "public"."quiz_questions" to "anon";
grant delete on table "public"."quiz_questions" to "authenticated";
grant insert on table "public"."quiz_questions" to "authenticated";
grant references on table "public"."quiz_questions" to "authenticated";
grant select on table "public"."quiz_questions" to "authenticated";
grant trigger on table "public"."quiz_questions" to "authenticated";
grant truncate on table "public"."quiz_questions" to "authenticated";
grant update on table "public"."quiz_questions" to "authenticated";
grant delete on table "public"."quiz_questions" to "service_role";
grant insert on table "public"."quiz_questions" to "service_role";
grant references on table "public"."quiz_questions" to "service_role";
grant select on table "public"."quiz_questions" to "service_role";
grant trigger on table "public"."quiz_questions" to "service_role";
grant truncate on table "public"."quiz_questions" to "service_role";
grant update on table "public"."quiz_questions" to "service_role";
grant delete on table "public"."quizzes" to "anon";
grant insert on table "public"."quizzes" to "anon";
grant references on table "public"."quizzes" to "anon";
grant select on table "public"."quizzes" to "anon";
grant trigger on table "public"."quizzes" to "anon";
grant truncate on table "public"."quizzes" to "anon";
grant update on table "public"."quizzes" to "anon";
grant delete on table "public"."quizzes" to "authenticated";
grant insert on table "public"."quizzes" to "authenticated";
grant references on table "public"."quizzes" to "authenticated";
grant select on table "public"."quizzes" to "authenticated";
grant trigger on table "public"."quizzes" to "authenticated";
grant truncate on table "public"."quizzes" to "authenticated";
grant update on table "public"."quizzes" to "authenticated";
grant delete on table "public"."quizzes" to "service_role";
grant insert on table "public"."quizzes" to "service_role";
grant references on table "public"."quizzes" to "service_role";
grant select on table "public"."quizzes" to "service_role";
grant trigger on table "public"."quizzes" to "service_role";
grant truncate on table "public"."quizzes" to "service_role";
grant update on table "public"."quizzes" to "service_role";
grant delete on table "public"."true_false_questions" to "anon";
grant insert on table "public"."true_false_questions" to "anon";
grant references on table "public"."true_false_questions" to "anon";
grant select on table "public"."true_false_questions" to "anon";
grant trigger on table "public"."true_false_questions" to "anon";
grant truncate on table "public"."true_false_questions" to "anon";
grant update on table "public"."true_false_questions" to "anon";
grant delete on table "public"."true_false_questions" to "authenticated";
grant insert on table "public"."true_false_questions" to "authenticated";
grant references on table "public"."true_false_questions" to "authenticated";
grant select on table "public"."true_false_questions" to "authenticated";
grant trigger on table "public"."true_false_questions" to "authenticated";
grant truncate on table "public"."true_false_questions" to "authenticated";
grant update on table "public"."true_false_questions" to "authenticated";
grant delete on table "public"."true_false_questions" to "service_role";
grant insert on table "public"."true_false_questions" to "service_role";
grant references on table "public"."true_false_questions" to "service_role";
grant select on table "public"."true_false_questions" to "service_role";
grant trigger on table "public"."true_false_questions" to "service_role";
grant truncate on table "public"."true_false_questions" to "service_role";
grant update on table "public"."true_false_questions" to "service_role";
grant delete on table "public"."weekly_quest_assignments" to "anon";
grant insert on table "public"."weekly_quest_assignments" to "anon";
grant references on table "public"."weekly_quest_assignments" to "anon";
grant select on table "public"."weekly_quest_assignments" to "anon";
grant trigger on table "public"."weekly_quest_assignments" to "anon";
grant truncate on table "public"."weekly_quest_assignments" to "anon";
grant update on table "public"."weekly_quest_assignments" to "anon";
grant delete on table "public"."weekly_quest_assignments" to "authenticated";
grant insert on table "public"."weekly_quest_assignments" to "authenticated";
grant references on table "public"."weekly_quest_assignments" to "authenticated";
grant select on table "public"."weekly_quest_assignments" to "authenticated";
grant trigger on table "public"."weekly_quest_assignments" to "authenticated";
grant truncate on table "public"."weekly_quest_assignments" to "authenticated";
grant update on table "public"."weekly_quest_assignments" to "authenticated";
grant delete on table "public"."weekly_quest_assignments" to "service_role";
grant insert on table "public"."weekly_quest_assignments" to "service_role";
grant references on table "public"."weekly_quest_assignments" to "service_role";
grant select on table "public"."weekly_quest_assignments" to "service_role";
grant trigger on table "public"."weekly_quest_assignments" to "service_role";
grant truncate on table "public"."weekly_quest_assignments" to "service_role";
grant update on table "public"."weekly_quest_assignments" to "service_role";
grant delete on table "public"."weekly_quest_challenge_submissions" to "anon";
grant insert on table "public"."weekly_quest_challenge_submissions" to "anon";
grant references on table "public"."weekly_quest_challenge_submissions" to "anon";
grant select on table "public"."weekly_quest_challenge_submissions" to "anon";
grant trigger on table "public"."weekly_quest_challenge_submissions" to "anon";
grant truncate on table "public"."weekly_quest_challenge_submissions" to "anon";
grant update on table "public"."weekly_quest_challenge_submissions" to "anon";
grant delete on table "public"."weekly_quest_challenge_submissions" to "authenticated";
grant insert on table "public"."weekly_quest_challenge_submissions" to "authenticated";
grant references on table "public"."weekly_quest_challenge_submissions" to "authenticated";
grant select on table "public"."weekly_quest_challenge_submissions" to "authenticated";
grant trigger on table "public"."weekly_quest_challenge_submissions" to "authenticated";
grant truncate on table "public"."weekly_quest_challenge_submissions" to "authenticated";
grant update on table "public"."weekly_quest_challenge_submissions" to "authenticated";
grant delete on table "public"."weekly_quest_challenge_submissions" to "service_role";
grant insert on table "public"."weekly_quest_challenge_submissions" to "service_role";
grant references on table "public"."weekly_quest_challenge_submissions" to "service_role";
grant select on table "public"."weekly_quest_challenge_submissions" to "service_role";
grant trigger on table "public"."weekly_quest_challenge_submissions" to "service_role";
grant truncate on table "public"."weekly_quest_challenge_submissions" to "service_role";
grant update on table "public"."weekly_quest_challenge_submissions" to "service_role";
grant delete on table "public"."weekly_quest_reminders" to "anon";
grant insert on table "public"."weekly_quest_reminders" to "anon";
grant references on table "public"."weekly_quest_reminders" to "anon";
grant select on table "public"."weekly_quest_reminders" to "anon";
grant trigger on table "public"."weekly_quest_reminders" to "anon";
grant truncate on table "public"."weekly_quest_reminders" to "anon";
grant update on table "public"."weekly_quest_reminders" to "anon";
grant delete on table "public"."weekly_quest_reminders" to "authenticated";
grant insert on table "public"."weekly_quest_reminders" to "authenticated";
grant references on table "public"."weekly_quest_reminders" to "authenticated";
grant select on table "public"."weekly_quest_reminders" to "authenticated";
grant trigger on table "public"."weekly_quest_reminders" to "authenticated";
grant truncate on table "public"."weekly_quest_reminders" to "authenticated";
grant update on table "public"."weekly_quest_reminders" to "authenticated";
grant delete on table "public"."weekly_quest_reminders" to "service_role";
grant insert on table "public"."weekly_quest_reminders" to "service_role";
grant references on table "public"."weekly_quest_reminders" to "service_role";
grant select on table "public"."weekly_quest_reminders" to "service_role";
grant trigger on table "public"."weekly_quest_reminders" to "service_role";
grant truncate on table "public"."weekly_quest_reminders" to "service_role";
grant update on table "public"."weekly_quest_reminders" to "service_role";
grant delete on table "public"."weekly_quest_weeks" to "anon";
grant insert on table "public"."weekly_quest_weeks" to "anon";
grant references on table "public"."weekly_quest_weeks" to "anon";
grant select on table "public"."weekly_quest_weeks" to "anon";
grant trigger on table "public"."weekly_quest_weeks" to "anon";
grant truncate on table "public"."weekly_quest_weeks" to "anon";
grant update on table "public"."weekly_quest_weeks" to "anon";
grant delete on table "public"."weekly_quest_weeks" to "authenticated";
grant insert on table "public"."weekly_quest_weeks" to "authenticated";
grant references on table "public"."weekly_quest_weeks" to "authenticated";
grant select on table "public"."weekly_quest_weeks" to "authenticated";
grant trigger on table "public"."weekly_quest_weeks" to "authenticated";
grant truncate on table "public"."weekly_quest_weeks" to "authenticated";
grant update on table "public"."weekly_quest_weeks" to "authenticated";
grant delete on table "public"."weekly_quest_weeks" to "service_role";
grant insert on table "public"."weekly_quest_weeks" to "service_role";
grant references on table "public"."weekly_quest_weeks" to "service_role";
grant select on table "public"."weekly_quest_weeks" to "service_role";
grant trigger on table "public"."weekly_quest_weeks" to "service_role";
grant truncate on table "public"."weekly_quest_weeks" to "service_role";
grant update on table "public"."weekly_quest_weeks" to "service_role";
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_profile_on_signup();
