drop extension if exists "pg_net";
create sequence "public"."weekly_quest_reminders_id_seq";
alter table "public"."imposter_game_lobbies" drop constraint if exists "fk_imposter_game_lobbies_current_concept";
alter table "public"."imposter_game_lobbies" drop constraint if exists "fk_imposter_game_lobbies_current_imposter";
alter table "public"."lesson_moderation_records" drop constraint if exists "lesson_moderation_records_decision_source_check";
alter table "public"."lesson_moderation_records" drop constraint if exists "lesson_moderation_records_event_type_check";
drop index if exists "public"."idx_imposter_game_lobbies_concept_result_deadline_at";
drop index if exists "public"."idx_imposter_game_lobbies_current_phase";
drop index if exists "public"."idx_imposter_game_lobbies_guess_deadline_at";
drop index if exists "public"."idx_imposter_game_lobbies_turn_ends_at";
drop index if exists "public"."idx_imposter_game_lobbies_voting_deadline_at";
create table "public"."weekly_quest_reminders" (
    "id" bigint not null default nextval('public.weekly_quest_reminders_id_seq'::regclass),
    "week_id" bigint not null,
    "reminder_type" character varying(50) not null,
    "sent_at" timestamp with time zone not null
      );
alter table "public"."weekly_quest_reminders" enable row level security;
alter table "public"."imposter_game_lobbies" drop column if exists "concept_count";
alter table "public"."imposter_game_lobbies" drop column if exists "concept_result_deadline_at";
alter table "public"."imposter_game_lobbies" drop column if exists "current_concept_index";
alter table "public"."imposter_game_lobbies" drop column if exists "current_concept_public_id";
alter table "public"."imposter_game_lobbies" drop column if exists "current_concept_title";
alter table "public"."imposter_game_lobbies" drop column if exists "current_drawer_learner_id";
alter table "public"."imposter_game_lobbies" drop column if exists "current_drawing_snapshot";
alter table "public"."imposter_game_lobbies" drop column if exists "current_imposter_learner_id";
alter table "public"."imposter_game_lobbies" drop column if exists "current_phase";
alter table "public"."imposter_game_lobbies" drop column if exists "current_turn_index";
alter table "public"."imposter_game_lobbies" drop column if exists "discussion_timer_seconds";
alter table "public"."imposter_game_lobbies" drop column if exists "drawing_version";
alter table "public"."imposter_game_lobbies" drop column if exists "imposter_guess_deadline_at";
alter table "public"."imposter_game_lobbies" drop column if exists "imposter_guess_timer_seconds";
alter table "public"."imposter_game_lobbies" drop column if exists "last_imposter_guess";
alter table "public"."imposter_game_lobbies" drop column if exists "last_imposter_guess_correct";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_accused_learner_id";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_concept_label";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_concept_number";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_imposter_guess";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_imposter_learner_id";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_imposter_wins_by_voting_tie";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_resolution";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_vote_tallies";
alter table "public"."imposter_game_lobbies" drop column if exists "latest_result_winner_side";
alter table "public"."imposter_game_lobbies" drop column if exists "max_voting_rounds";
alter table "public"."imposter_game_lobbies" drop column if exists "player_scores";
alter table "public"."imposter_game_lobbies" drop column if exists "round_completed_at";
alter table "public"."imposter_game_lobbies" drop column if exists "round_drawer_order";
alter table "public"."imposter_game_lobbies" drop column if exists "round_number";
alter table "public"."imposter_game_lobbies" drop column if exists "rounds_per_concept";
alter table "public"."imposter_game_lobbies" drop column if exists "state_version";
alter table "public"."imposter_game_lobbies" drop column if exists "turn_completed_at";
alter table "public"."imposter_game_lobbies" drop column if exists "turn_duration_seconds";
alter table "public"."imposter_game_lobbies" drop column if exists "turn_ends_at";
alter table "public"."imposter_game_lobbies" drop column if exists "turn_started_at";
alter table "public"."imposter_game_lobbies" drop column if exists "used_concept_public_ids";
alter table "public"."imposter_game_lobbies" drop column if exists "voted_out_learner_id";
alter table "public"."imposter_game_lobbies" drop column if exists "voting_ballots";
alter table "public"."imposter_game_lobbies" drop column if exists "voting_deadline_at";
alter table "public"."imposter_game_lobbies" drop column if exists "voting_eligible_target_learner_ids";
alter table "public"."imposter_game_lobbies" drop column if exists "voting_round_number";
alter table "public"."imposter_game_lobbies" enable row level security;
alter table "public"."imposter_game_lobby_members" enable row level security;
alter table "public"."imposter_monthly_pack_concepts" enable row level security;
alter table "public"."imposter_monthly_pack_weekly_features" enable row level security;
alter table "public"."imposter_monthly_packs" enable row level security;
alter table "public"."learners" add column "bio" text;
alter table "public"."learners" add column "profile_picture" text;
alter sequence "public"."weekly_quest_reminders_id_seq" owned by "public"."weekly_quest_reminders"."id";
CREATE UNIQUE INDEX weekly_quest_reminders_pkey ON public.weekly_quest_reminders USING btree (id);
CREATE INDEX weekly_quest_reminders_type_sent_at_idx ON public.weekly_quest_reminders USING btree (reminder_type, sent_at);
CREATE INDEX weekly_quest_reminders_week_id_idx ON public.weekly_quest_reminders USING btree (week_id);
alter table "public"."weekly_quest_reminders" add constraint "weekly_quest_reminders_pkey" PRIMARY KEY using index "weekly_quest_reminders_pkey";
alter table "public"."weekly_quest_reminders" add constraint "weekly_quest_reminders_week_id_fkey" FOREIGN KEY (week_id) REFERENCES public.weekly_quest_weeks(id) not valid;
alter table "public"."weekly_quest_reminders" validate constraint "weekly_quest_reminders_week_id_fkey";
alter table "public"."lesson_moderation_records" add constraint "lesson_moderation_records_decision_source_check" CHECK (((decision_source)::text = ANY ((ARRAY['AUTO'::character varying, 'AUTO_FALLBACK'::character varying, 'ADMIN'::character varying])::text[]))) not valid;
alter table "public"."lesson_moderation_records" validate constraint "lesson_moderation_records_decision_source_check";
alter table "public"."lesson_moderation_records" add constraint "lesson_moderation_records_event_type_check" CHECK (((event_type)::text = ANY ((ARRAY['AUTO_APPROVED'::character varying, 'AUTO_REJECTED'::character varying, 'AUTO_FLAGGED'::character varying, 'AUTO_FAILED'::character varying, 'ADMIN_APPROVED'::character varying, 'ADMIN_REJECTED'::character varying])::text[]))) not valid;
alter table "public"."lesson_moderation_records" validate constraint "lesson_moderation_records_event_type_check";
grant delete on table "public"."weekly_quest_reminders" to "anon";
grant insert on table "public"."weekly_quest_reminders" to "anon";
grant references on table "public"."weekly_quest_reminders" to "anon";
grant select on table "public"."weekly_quest_reminders" to "anon";
grant trigger on table "public"."weekly_quest_reminders" to "anon";
grant truncate on table "public"."weekly_quest_reminders" to "anon";
grant update on table "public"."weekly_quest_reminders" to "anon";
grant delete on table "public"."weekly_quest_reminders" to "authenticated";
grant insert on table "public"."weekly_quest_reminders" to "authenticated";
grant references on table "public"."weekly_quest_reminders" to "authenticated";
grant select on table "public"."weekly_quest_reminders" to "authenticated";
grant trigger on table "public"."weekly_quest_reminders" to "authenticated";
grant truncate on table "public"."weekly_quest_reminders" to "authenticated";
grant update on table "public"."weekly_quest_reminders" to "authenticated";
grant delete on table "public"."weekly_quest_reminders" to "service_role";
grant insert on table "public"."weekly_quest_reminders" to "service_role";
grant references on table "public"."weekly_quest_reminders" to "service_role";
grant select on table "public"."weekly_quest_reminders" to "service_role";
grant trigger on table "public"."weekly_quest_reminders" to "service_role";
grant truncate on table "public"."weekly_quest_reminders" to "service_role";
grant update on table "public"."weekly_quest_reminders" to "service_role";
